version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgres

  app:
    image: kinmkd
    depends_on:
      - postgres
    build: ./
    restart: on-failure
    ports:
      - '6868:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/postgres",
          "spring.datasource.username" : "postgres",
          "spring.datasource.password" : "admin",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
